#!/usr/bin/env sh

host=${SME_HOST:="localhost"}
port=${SME_PORT:="8080"}

url="http://$host:$port"

echo "Server will run on $url"

# open $url &
# node api.js &
#webpack --progress --watch
webpack-dev-server --history-api-fallback --inline --progress --devtool source-map --host $host --port $port
